builders:
  flutter_widget_skewer:
    import: "package:flutter_widget_skewer/flutter_widget_skewer.dart"
    builder_factories: ["flutterWidgetSkewerBuilder"]
    build_extensions: { r'lib': ['flutter_widget_suger.g.dart'] }
    build_to: source
    auto_apply: root_package
