name: flutter_widget_skewer
description: A Dart code generator that makes Flutter widgets chainable like skewers. With widget_skewer, you can build widget trees with extension methods instead of nesting braces.
version: 0.0.5
repository: https://github.com/zyzdev/flutter_widget_skewer

topics:
  - build-runner
  - codegen

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  analyzer: ^7.0.0
  build_runner: ^2.0.0
  build: ^2.3.1
  collection: ^1.15.0
  path: ^1.8.0

dev_dependencies:
  lints: